---
- name: install pip
  apt:
          name: python-pip
          state: latest

- name: install docker-py for ansible docker modules
  command: pip install docker-py

- name: create build env for Docker
  file:
          path: /tmp/webapp_owncloud
          state: directory

- name: create Dockerfile
  template:
          src: Dockerfile.j2
          dest: /tmp/webapp_owncloud/Dockerfile
          owner: www-data
          group: www-data

- name: mount data storage
  mount:
    path: /var/owncloud_data
    src: "{{ storage_location }}"
    state: mounted
    fstype: nfs

- name: mount configuration storage
  mount:
    path: /var/owncloud_config
    src: "{{ config_location }}"
    state: mounted
    fstype: nfs

- name: build Docker image
  docker_image:
    path: /tmp/webapp_owncloud
    name: g3/owncloud

- name: run docker container in port 80
  docker_container:
          name: owncloud_webapp
          volumes: 
            - /var/owncloud_data:/var/www/data
            - /var/owncloud_config:/var/www/html/config
          published_ports:
            - 80:80
          image: g3/owncloud 
          detach: false
  async: 3
  poll: 0

- name: Check if the configuration files exist
  stat:
     path: /var/owncloud_config/config.php
  register: stat_result

- name: Check if configuration file is valid
  become_user: www-data
  shell: grep "'installed' => true," /var/owncloud_config/config.php
  register: test_grep
  when: stat_result.stat.exists == True 
  ignore_errors: yes

- name: Configures owncloud if not initialized
  shell: docker exec owncloud_webapp sudo -u www-data php occ maintenance:install \
        --database "mysql" \
        --database-host "{{ master_db }}" --database-name "owncloud" \
        --database-user "owncloud" --database-pass "12345" \
        --admin-user "admin" --admin-pass "admin" \
        --data-dir "/var/www/data"
  run_once: true
  when: stat_result.stat.exists == False or test_grep.stdout == ""

- name: add server location to trusted domains
  shell: docker exec owncloud_webapp \
         sudo -u www-data php occ config:system:set \
         trusted_domains {{ inventory_hostname }} --value={{ inventory_hostname }}
