---
#- name: copy Dockerfile 
#  copy:
#          src: Dockerfile
#          dest: /tmp/Dockerfile
#

- name: create build env for Docker
  file:
          path: /tmp/webapp_owncloud
          state: directory

- name: create Dockerfile
  template:
          src: Dockerfile.j2
          dest: /tmp/webapp_owncloud/Dockerfile
          owner: www-data
          group: www-data

#- name: create configuration file
#  template:
#          src: config.j2
#          dest: /tmp/config.php
#          owner: www-data
#          group: www-data


- name: create mount point 
  file:
    path: /var/owncloud_data
    state: directory
    owner: www-data
    group: www-data

- name: mount storage
  command: "mount {{ storage_location }} /var/owncloud_data"

- name: build Docker image
  command: docker build -t g3/owncloud /tmp/webapp_owncloud

- name: run docker container in port 80
  shell: docker run -v /var/owncloud_data:/var/www/data -p 80:80 g3/owncloud 
  async: 3
  poll: 0

