---
#- name: copy Dockerfile 
#  copy:
#          src: Dockerfile
#          dest: /tmp/Dockerfile
#

- name: create Dockerfile
  template:
          src: Dockerfile.j2
          dest: /tmp/Dockerfile
          owner: www-data
          group: www-data

#- name: create configuration file
#  template:
#          src: config.j2
#          dest: /tmp/config.php
#          owner: www-data
#          group: www-data

- name: build Docker image
  command: docker build -t g3/owncloud /tmp  

- name: run docker container in port 80
  shell: docker run -p 80:80 g3/owncloud 
  async: 3
  poll: 0

