---
- name: install nfs dependencies
  apt: 
    name: "nfs-kernel-server"
    state: latest
    update_cache: yes

- name: check if data directory was already created (for idempotence)
  stat: 
    path: "/var/owncloud_data"
  register: data_folder

- name: setup directory for owncloud data
  file: 
    path: "/var/owncloud_data"
    state: directory
    owner: www-data
    group: www-data

- name: add /var/data to export
  lineinfile:
      path: /etc/exports
      line: "/var/owncloud_data  *(rw,sync)"
      insertafter: EOF
  notify:
      restart nfs
  when: not (data_folder.stat.isdir is defined and data_folder.stat.isdir)

- name: check if config directory was already created (for idempotence)
  stat: 
    path: "/var/owncloud_config"
  register: config_folder

- name: setup directory for owncloud configuration
  file: 
    path: "/var/owncloud_config"
    state: directory
    owner: www-data
    group: www-data

- name: add /var/config to export
  lineinfile:
      path: /etc/exports
      line: "/var/owncloud_config  *(rw,sync)"
      insertafter: EOF
  notify:
      restart nfs
  when: not (config_folder.stat.isdir is defined and config_folder.stat.isdir)

- name: 
  shell: exportfs -a
# add rule in case there is a firewall?
