- name: pull elastic search docker image
  docker_image:
    name: docker.elastic.co/elasticsearch/elasticsearch-oss
    tag: 6.1.1
    pull: yes

- name: pull kibana docker image
  docker_image:
    name: docker.elastic.co/kibana/kibana-oss
    tag: 6.1.1
    pull: yes

- name: increase memory capacity
  command: sysctl -w vm.max_map_count=262144

- name: run elastic_search 
  docker_container:
    name: e_search
    published_ports:
      - 9200:9200
      - 9300:9300 
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1

- name: run kibana
  docker_container: 
    name: kibana
    published_ports:
      - 80:5601
    image: docker.elastic.co/kibana/kibana-oss:6.1.1
    links:
      - e_search:elasticsearch



