---
- name: add docker repo key
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 0EBFCD88
    state: present

- name: add docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: install required software
  apt:
    name: "{{ item }}"
    state: latest
  with_items: 
#    - software-properties-common 
#    - curl
#    - apt-transport-https 
#    - ca-certificates 
    - docker-ce
#    - nfs-common

#- name: download and install docker-compose
#  get_url: 
#        url: https://github.com/docker/compose/releases/download/1.16.1/docker-compose-linux-x86_64 
#        dest: /usr/local/bin/docker-compose
#        mode: u+x
#
- name: install pip
  apt:
          name: python-pip
          state: latest

- name: install docker-py for ansible docker modules
  command: pip install docker-py


